### ISSUE TITLE
rechartsExample

### ISSUE THREAD

**Issue by Lchiffon** [jeevanyue/echarter#1]
要么老老实实引用
要么加author
要么好好把代码改一改

别人的代码去掉注释写进来， 只是在readme里面加一句`参考了XXX`不合适，基本的小函数就算了， 这个起码算是个功能函数吧...

**Comment by jeevanyue** [comment]
抱歉，第一次开发package，代码引用姿势不对。
因为生成echarts要用``echart()``，没办法直接引用，只是最后一小段做了少许改造。
我之前在docs/03-examples.Rmd加了下面一小段内容。
> echartsExample取自于[cosname/recharts](https://github.com/cosname/recharts)。

现在我在docs/03-examples.Rmd加入了作者信息和改动内容，并把相应内容也加入到代码注释中。
> ``echartsExample``引用的是[cosname/recharts](https://github.com/cosname/recharts)的``echartsExample``，作者[Lchiffon](https://github.com/Lchiffon)。只是最后一小段做了少许改动，以适用``echart()``。

不知道这样合不合适。
另外我还引用了很多``highcharter``的函数，我会后续按照您的建议按类似的方式补上。
