### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by lxj4321** [jeevanyue/echarter#4]
devtools::install_github("jeevanyue/echarter")

Error in dirname(name) : file name conversion problem -- name too long?
>

**Comment by lxj4321** [comment]
install.packages("C:/echarter-master.zip", repos = NULL, type = "win.binary")
Error in install.packages : invalid multibyte string at '<8a>.<74>xt'

**Comment by jeevanyue** [comment]
You can try to install the latest devtools.
