### ISSUE TITLE
在shiny中如何响应input的变化作图

### ISSUE THREAD

**Issue by feiwuu638** [jeevanyue/echarter#6]
您好，请问在shiny中使用echarter时，可以响应input的变化来做图吗，例如根据selectInput来改变做出的图。代码如下，报错：object 'input' not found。

`
server <- function(input, output) {
    output$test1 <- renderEcharts({
    dat <- battleData[c('球员','对手',input$chooseData)]
    echart() %>%
      ec_add_series(
        data = dat, type = "heatmap",
        mapping = ecaes(x = 球员, y = 对手, value = get(input$chooseData))) %>%
      ec_tooltip(
        trigger = 'item',
        formatter = '{b}:{c}') %>%
      ec_visualMap(
        min = 0, max = max(dat[3]),  type = 'continuous', calculable = TRUE,
        left = 'center', orient = 'horizontal') %>% 
      ec_axisPointer(show = TRUE, type = 'line')
  })
}

ui <- fluidPage(
    selectInput('chooseData','请选择想查看的数据类型：',
                                           choices = c(data_vector,'胜率'='胜率'),selected = '得分')
    echartsOutput('test1')
  )
 
shinyApp(ui = ui, server = server)
`

**Comment by jeevanyue** [comment]
@feiwuu638 可以的，只是`ecaes()`不会对`input$chooseData`进行计算，建议先对数据做好预处理。下面是一个简单案例。
```r
weekDays <- c('Mon','Tues','Wed','Thurs','Fri','Sat','Sun')
dat <- data.frame(
  saleNum = round(runif(21, 20, 100), 0),
  fruit = c(rep("Apple", 7), rep("Pear", 7), rep("Banana", 7)),
  weekDay = c(rep(weekDays, 3)),
  price = round(runif(21, 10, 20), 0),
  stringsAsFactors = FALSE)

server <- function(input, output) {
  output$test1 <- renderEcharts({
    dat_choose <- select(dat, weekDay, fruit, value = input$chooseData)
    echart() %>%
      ec_add_series(
        data = dat_choose, type = "heatmap",
        mapping = ecaes(x = weekDay, y = fruit, value = value)) %>%
      ec_tooltip(
        trigger = 'item',
        formatter = '{b}:{c}') %>%
      ec_visualMap(
        min = min(dat_choose$value), max = max(dat_choose$value), type = 'continuous', calculable = TRUE,
        left = 'center', orient = 'horizontal') %>%
      ec_axisPointer(show = TRUE, type = 'line')
  })
}

ui <- fluidPage(
  selectInput('chooseData','请选择想查看的数据类型：',
              choices = c("saleNum", "price"), selected = "saleNum"),
  echartsOutput('test1')
)

shinyApp(ui = ui, server = server)
```

**Comment by feiwuu638** [comment]
@jeevanyue 明白了，谢谢！
